language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: mV244LZes8Qy7Lb1J+bXCU5ppIs2ywafJwXvzmDb3bZMQbvPw5irME3cpydLmDaCbiQDPeMqSJUL3oJCV6tbn29P48drwYl0EM30BBfeiwVTMv7c82UiBK1nOYZJ/iLVgPKhbM2iyOj0eI8u9Uw0iIIvFsuFTU3TPHBKFdP0j2RdwbnoGCn+wrYc724dtRsO4ubcVWUH6jPROvFUa7bp/Hp16fCxuMsT5rHv09AYIIvoxUDPuULoIwPyLd7ld6c5sUOP/x8Pif/fukEV16vkxWIzkwmjWqslx0c6vGU8O3KHH3CsbLpspmxKiu7dO+uejSOBVepMMKghfq6eLlvXPg3UQ1P/5Svi06Tu11LgWEBeiUParsZHKJwHVuesWN281ybqWODB6dE7smGyynpyLeJCyxR73J6AjXfORw758kPt2C8ivBRMK/uW6gzbdDQmgsg3ZUhDqCEqGM4080cERJAptel1eyPW4lEVV0A7dSM4xVKqh3P+Rpeg4vrLMdgCMcH37txTQiBj0uS9gMCNHMuqQyMWYQ5QH4wTQ9CXGOQWk5EOqx06rPi9SV37Zdj0Qh7ZjJc1FORrVs07vUymRnemlIVZqCjZzfBJFi8x+G5Uo50lFWLqaHrkteW24ZzO6aNm0oqTmjBlN1ikiXUddI69sYtwylocknMlXlpGhsg=
  app: codex-notes
  on:
    repo: nikhilkamineni/codex
